"""Authentication endpoints — register, login, refresh, logout, me."""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from loguru import logger

from app.core.security import (
    create_access_token,
    create_refresh_token,
    decode_token,
    hash_password,
    verify_password,
)
from app.db.database import get_db
from app.models.user import User
from app.schemas.auth import (
    LoginInput,
    RefreshInput,
    RegisterInput,
    TokenResponse,
    UserResponse,
)
from app.api.v1.dependencies import get_current_active_user

router = APIRouter(prefix="/auth", tags=["auth"])


@router.post("/register", response_model=TokenResponse, status_code=201)
async def register(data: RegisterInput, db: AsyncSession = Depends(get_db)):
    logger.info(f"📝 Registration attempt for email: {data.email}")

    try:
        await db.execute(select(1))
    except Exception as e:
        logger.error(f"❌ Database connection error during registration: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Database service temporarily unavailable. Please try again later.",
        )

    try:
        result = await db.execute(select(User).where(User.email == data.email))
        existing_user = result.scalar_one_or_none()
        if existing_user:
            logger.warning(f"⚠️ Registration failed: Email already registered - {data.email}")
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="Email already registered. Please login or use a different email.",
            )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"❌ Error checking duplicate email: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Error validating email. Please try again.",
        )

    try:
        hashed_pw = hash_password(data.password)
        user = User(
            name=data.name.strip(),
            email=data.email.lower(),
            hashed_password=hashed_pw,
            language=data.language or "English",
            state=data.state,
            occupation=data.occupation,
        )
        db.add(user)
        await db.flush()
        if not user.id:
            raise ValueError("User ID was not generated by database")
        await db.commit()
        await db.refresh(user)
        logger.info(f"✅ User successfully registered: {user.email} (ID: {user.id})")
    except HTTPException:
        await db.rollback()
        raise
    except Exception as e:
        logger.error(f"❌ Unexpected error during user creation: {str(e)}", exc_info=True)
        await db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Registration failed due to a server error. Please try again later.",
        )

    try:
        access_token = create_access_token(user.id)
        refresh_token = create_refresh_token(user.id)
        logger.info(f"🎉 Registration completed successfully for: {user.email}")
        return TokenResponse(access_token=access_token, refresh_token=refresh_token)
    except Exception as e:
        logger.error(f"❌ Unexpected error during token generation: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to complete registration. Please try again.",
        )


@router.post("/login", response_model=TokenResponse)
async def login(data: LoginInput, db: AsyncSession = Depends(get_db)):
    logger.info(f"🔐 Login attempt for email: {data.email}")
    try:
        result = await db.execute(select(User).where(User.email == data.email.lower()))
        user = result.scalar_one_or_none()
        if not user or not verify_password(data.password, user.hashed_password):
            logger.warning(f"⚠️ Login failed: Invalid credentials for {data.email}")
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid email or password",
            )
        if not user.is_active:
            logger.warning(f"⚠️ Login blocked: Account is deactivated - {data.email}")
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Your account has been deactivated. Please contact support.",
            )
        access_token = create_access_token(user.id)
        refresh_token = create_refresh_token(user.id)
        logger.info(f"✅ Login successful for: {data.email}")
        return TokenResponse(access_token=access_token, refresh_token=refresh_token)
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"❌ Unexpected error during login: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Login failed due to a server error. Please try again later.",
        )


@router.post("/refresh", response_model=TokenResponse)
async def refresh(data: RefreshInput, db: AsyncSession = Depends(get_db)):
    logger.debug("🔄 Token refresh attempt")
    try:
        payload = decode_token(data.refresh_token)
    except ValueError as e:
        logger.warning(f"⚠️ Invalid refresh token: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired refresh token",
        )

    if payload.get("type") != "refresh":
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token type")

    user_id = payload.get("sub")
    if not user_id:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token payload")

    try:
        result = await db.execute(select(User).where(User.id == user_id))
        user = result.scalar_one_or_none()
        if not user:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="User not found")
        if not user.is_active:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="User account is inactive")
        access_token = create_access_token(user.id)
        refresh_token = create_refresh_token(user.id)
        logger.debug(f"✅ Tokens refreshed for user: {user_id}")
        return TokenResponse(access_token=access_token, refresh_token=refresh_token)
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"❌ Unexpected error during token refresh: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Token refresh failed. Please login again.",
        )


@router.post("/logout")
async def logout():
    logger.debug("🚪 Logout request")
    return {"message": "Logged out successfully"}


@router.get("/me", response_model=UserResponse)
async def me(current_user: User = Depends(get_current_active_user)):
    logger.debug(f"📋 Profile requested for user: {current_user.id}")
    return current_user
